<script lang="ts">
  import {
    House,
    LayoutGrid,
    CalendarDays,
    BookOpen,
    Settings,
    Plus,
    Search,
    ArrowRight,
    ArrowLeft,
    ChevronLeft,
    ChevronRight,
    Check,
    X,
    MoreHorizontal,
    Clock,
    Pencil,
    Trash2,
    Bell,
    Sprout,
    Cat,
    Flower2,
    Bath,
    CookingPot,
    BedDouble,
    Sofa,
    Car,
    Box,
    Droplets,
    Brush,
    Waves,
    Eye,
    Scissors,
    Milk,
    Sun,
    Sparkles,
    Wind,
    Cloud,
    ShieldCheck,
    Moon,
    Monitor,
    Download,
    Upload,
    RotateCcw,
    AlertCircle,
    Leaf,
    SlidersHorizontal,
    HelpCircle,
    Heart,
    Star,
    CheckCheck,
    Archive,
    LoaderCircle,
    ChevronDown,
    Toothbrush,
    ShowerHead,
    TowelRack,
    WashingMachine,
    Refrigerator,
    Microwave,
    Utensils,
    Coffee,
    Pill,
    PillBottle,
    PawPrint,
    Dog,
    Lamp,
    Armchair,
    Book,
    Baby,
    Wrench,
    Plug,
    SprayCan,
    RobotVacuum,
    PlantPot,
    AlarmSmoke,
  } from '@lucide/svelte';
  import type { Component } from 'svelte';
  let {
    name,
    size = 20,
    stroke = 1.8,
    class: cls = '',
  }: {
    name: string;
    size?: number;
    stroke?: number;
    class?: string;
  } = $props();
  const icons: Record<string, Component<any>> = {
    home: House,
    objects: LayoutGrid,
    calendar: CalendarDays,
    history: BookOpen,
    settings: Settings,
    plus: Plus,
    search: Search,
    arrow: ArrowRight,
    back: ArrowLeft,
    left: ChevronLeft,
    right: ChevronRight,
    check: Check,
    close: X,
    more: MoreHorizontal,
    clock: Clock,
    edit: Pencil,
    delete: Trash2,
    bell: Bell,
    sprout: Sprout,
    cat: Cat,
    flower: Flower2,
    bath: Bath,
    'cooking-pot': CookingPot,
    bed: BedDouble,
    sofa: Sofa,
    car: Car,
    box: Box,
    droplets: Droplets,
    brush: Brush,
    waves: Waves,
    eye: Eye,
    scissors: Scissors,
    milk: Milk,
    bottle: Milk,
    sun: Sun,
    sparkles: Sparkles,
    wind: Wind,
    cloud: Cloud,
    shield: ShieldCheck,
    moon: Moon,
    monitor: Monitor,
    download: Download,
    upload: Upload,
    undo: RotateCcw,
    alert: AlertCircle,
    leaf: Leaf,
    sliders: SlidersHorizontal,
    help: HelpCircle,
    heart: Heart,
    star: Star,
    completed: CheckCheck,
    archive: Archive,
    loading: LoaderCircle,
    down: ChevronDown,
    sponge: Box,
    toothbrush: Toothbrush,
    'shower-head': ShowerHead,
    'towel-rack': TowelRack,
    'washing-machine': WashingMachine,
    refrigerator: Refrigerator,
    microwave: Microwave,
    utensils: Utensils,
    coffee: Coffee,
    pill: Pill,
    'pill-bottle': PillBottle,
    'paw-print': PawPrint,
    dog: Dog,
    lamp: Lamp,
    armchair: Armchair,
    'bed-double': BedDouble,
    book: Book,
    baby: Baby,
    wrench: Wrench,
    plug: Plug,
    'spray-can': SprayCan,
    'robot-vacuum': RobotVacuum,
    'plant-pot': PlantPot,
    'alarm-smoke': AlarmSmoke,
  };
  const Glyph = $derived(icons[name] ?? Box);
</script>

<Glyph {size} strokeWidth={stroke} class={cls} aria-hidden="true" />
